### ISSUE TITLE
We need a text that explains how the game will actually work.

### ISSUE THREAD

**Issue by Nycrera** [Nycrera/p-game#1]
So yeah we need text in our wiki presumably that explains how this game will going to get played. Simple game mechanics and rules.

Here is the wiki : [P-Game Wiki Page](https://github.com/Nycrera/p-game/wiki)

**Comment by efeemir103** [comment]
allright my nigga ill write that ^-^

**Comment by efeemir103** [comment]
i wrote check out :+1: :smile:
